version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:4.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster-1
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka-data:/bitnami/kafka
    restart: unless-stopped
  mongo:
    image: mongo:7
    command: [ "--replSet", "rs0" ]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./docker/init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
    restart: unless-stopped

volumes:
  kafka-data:
  mongo-data:
